//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using UnityEngine;

[Serializable]
[XmlRoot(ElementName = "Node")]
public class Connection
{
	private Node startNode;
	private Node endNode;
	private bool isBidirectional;

	[OptionalField]
	private double speed = 3.0;

	public Node StartNode {
		get {return startNode;}
		set {startNode = value;}
	}

	public Node EndNode {
		get {return endNode;}
		set {endNode = value;}
	}

	public bool Bidirectional {
		get {return isBidirectional;}
		set {isBidirectional = value;}
	}

	public double Speed {
		get { return speed; }
		set { speed = value; }
	}

	[OnDeserializing]
	public void SetSpeedDefaultValue(StreamingContext context) {
		speed = 3.0;
	}




}