//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Connection
{
	private Node startNode;
	private Node endNode;
	private bool isBidirectional;

	public Node StartNode {
		get {return startNode;}
		set {startNode = value;}
	}

	public Node EndNode {
		get {return endNode;}
		set {endNode = value;}
	}

	public bool Bidirectional {
		get {return isBidirectional;}
		set {isBidirectional = value;}
	}

}