//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Connection : MonoBehaviour
{
	private Node startNode;
	private Node endNode;
	bool isBidirectional;

	/*
	public Connection (Node startNode, Node endNode, bool isBidirectional)
	{
		this.startNode = startNode;
		this.endNode = endNode;
		this.isBidirectional = isBidirectional;
	}
	*/

	public Node StartNode {
		get {return startNode;}
		set {startNode = value;}
	}

	public Node EndNode {
		get {return endNode;}
		set {endNode = value;}
	}

	public bool Bidirectional {
		get {return isBidirectional;}
		set {isBidirectional = value;}
	}

	public void UpdatePosition() {
		Vector3 startPosition = startNode.gameObject.transform.position;
		Vector3 endPosition = endNode.gameObject.transform.position;
		gameObject.transform.position = (startPosition + endPosition) / 2.0f;
		gameObject.transform.localScale = new Vector3(Vector3.Distance(endPosition, startPosition), 0.1f, 0.01f);
		gameObject.transform.rotation = Quaternion.FromToRotation(new Vector3(1, 0, 0), startPosition - endPosition);

		if (isBidirectional) {
			gameObject.transform.FindChild("Unidirectional").GetComponent<SpriteRenderer>().enabled = false;
			gameObject.transform.FindChild("Bidirectional").GetComponent<SpriteRenderer>().enabled = true;
		} else {
			gameObject.transform.FindChild("Unidirectional").GetComponent<SpriteRenderer>().enabled = true;
			gameObject.transform.FindChild("Bidirectional").GetComponent<SpriteRenderer>().enabled = false;
		}
	}

}