//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Node : MonoBehaviour
{
	private int id;

	public int Id {
		get {return id;}
		set {id = value;}
	}
	
	public Vector3 Position {
		get {this.gameObject.transform.position;}
		set {this.game.transform.position = value;}
	}
}


