//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Node : MonoBehaviour
{
	private int id;
	private List<Connection> connections = new List<Connection>();

	public int Id {
		get {return id;}
		set {id = value;}
	}
	
	public Vector3 Position {
		get {return this.gameObject.transform.position;}
		set {
			this.gameObject.transform.position = value;
			foreach (Connection connection in connections) {
				connection.UpdatePosition();
			}
		}
	}

	public void AddConnection(Connection connection) {
		connections.Add(connection); 
	}

	public void OnMouseDrag() {
		RaycastHit2D ray = Physics2D.Raycast(Camera.main.ScreenToWorldPoint(Input.mousePosition), Vector2.zero);
		Position = new Vector3(ray.point.x, ray.point.y, -1);
	}
}


