//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class SingleDirectionTool : MonoBehaviour
{
	public GameObject map;
	public double segmentLength = 2;
	private double previousPosition;

	/**
	 * State machine state
	 *   0 - Not started
	 *   1 - Started
	 *   2 - Finish
	 */
	private int state = 0;

	public SingleDirectionTool ()
	{
		state = 0;
	}

	public void RespondMouseClick() {
		print (map.ToString());
		RaycastHit2D ray = Physics2D.Raycast(Camera.main.ScreenToWorldPoint(Input.mousePosition), Vector2.zero);
		switch (state) {
		case 0:
			if(ray.collider != null){


			}
			state = 1;
			break;
		case 1:
			if (ray.collider != null) {
				Vector3 targetPosition = ray.point;
			}
			break;
		default:
			break;
		}
	}


}


