//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Node
{
	private int id;
	private MapController map;
	private Vector3 position;
	private List<Connection> connections = new List<Connection>();

	public int Id {
		get {return id;}
		set {id = value;}
	}

	public MapController Map {
		get { return map; }
		set { map = value; }
	}

	public Vector3 Position {
		get {return position;}
		set {position = value;}
	}

	public void AddConnection(Connection connection) {
		connections.Add(connection); 
	}

	public void RemoveConnection(Connection connection) {
		connections.Remove(connection); 
	}
}


