//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Xml.Serialization;
using UnityEngine;

[Serializable()]
public class Node
{
	private int id;
	private double x, y;

	public int Id {
		get {return id;}
		set {id = value;}
	}

	public double X {
		get { return x; }
		set { x = value; }
	}

	public double Y { 
		get { return y; }
		set { y = value; }
	}
}


